version: "3.9"
services:
  challenge-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - app-network

  challenge-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: "mongo:4.4.19"
    container_name: "mongodb"
    ports:
      - "27017:27017"
    networks:
      - app-network

  nginx:
    image: "nginx:1.21"
    container_name: "nginx"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - challenge-frontend
      - challenge-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge